title: Lee A. Werner # your name (or website title) here
logo: "/images/headshot_circle.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Business Data Analyst at Ecolab
  <br><br>
  Passionate about data science and working with people.
  <br><br>
  <a href="/pdf/reg-model.pdf">View My LinkedIn Profile</a>
  <br>
  <a href="https://www.linkedin.com/in/lee-werner/">View My LinkedIn Profile</a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
